Repository NVIDIA/deepops, pull requests merged in 2020-08, with the labels that each got.

#611 Update RHEL GPG key url for nvidia-dgx role.
  roles/nvidia-dgx/defaults/main.yml
Labels: critical-bug, next-release

#610 Update Pyxis to v0.8.0
  config.example/group_vars/slurm-cluster.yml
  roles/pyxis/defaults/main.yml
  roles/pyxis/tasks/pyxis.yml
Labels: next-release

#612 Update Slurm version to 20.02.4
  config.example/group_vars/slurm-cluster.yml
  roles/slurm/defaults/main.yml
Labels: next-release

#597 Slurm role enhance, cleanup, re-org
  config.example/group_vars/all.yml
  roles/slurm/defaults/main.yml
  roles/slurm/files/slurmctld.service
  roles/slurm/files/slurmd.service
  roles/slurm/files/slurmdbd.service
  roles/slurm/tasks/build.yml
  roles/slurm/tasks/compute.yml
  roles/slurm/tasks/controller.yml
  roles/slurm/tasks/munge.yml
  roles/slurm/tasks/prolog_epilog.yml
  roles/slurm/templates/cgroup.conf
  roles/slurm/templates/etc/ld.so.conf.d/slurm.conf.j2
  roles/slurm/templates/etc/localusers
  roles/slurm/templates/etc/munge/munge.key.j2
  roles/slurm/templates/etc/slurm/cgroup.conf
  roles/slurm/templates/etc/slurm/epilog.d/40-lastuserjob-processes
  roles/slurm/templates/etc/slurm/epilog.d/41-lastuserjob-ssh
  roles/slurm/templates/etc/slurm/epilog.d/50-all-enroot-dirs
  roles/slurm/templates/etc/slurm/epilog.d/50-exclusive-gpu
  roles/slurm/templates/etc/slurm/epilog.d/60-exclusive-cpu
  roles/slurm/templates/etc/slurm/epilog.d/80-exclusive-tmpfiles
  roles/slurm/templates/etc/slurm/epilog.sh
  roles/slurm/templates/etc/slurm/gres.conf
  roles/slurm/templates/etc/slurm/prolog.d/50-all-enroot-dirs
  roles/slurm/templates/etc/slurm/prolog.d/50-exclusive-cpu
  roles/slurm/templates/etc/slurm/prolog.d/50-exclusive-gpu
  roles/slurm/templates/etc/slurm/prolog.d/50-exclusive-ssh
  roles/slurm/templates/etc/slurm/prolog.sh
  roles/slurm/templates/etc/slurm/shared/bin/run-parts.sh
  roles/slurm/templates/etc/slurm/shared/bin/set_gpu_clocks.sh
  roles/slurm/templates/etc/slurm/shared/bin/set_gpu_power_levels.sh
  roles/slurm/templates/etc/slurm/slurm.conf
  roles/slurm/templates/etc/slurm/slurmdbd.conf
Labels: next-release

#493 Fix handling of services when downgrading Slurm
  roles/slurm/tasks/build.yml
  roles/slurm/tasks/compute.yml
  roles/slurm/tasks/controller.yml
Labels: enhancement

#603 Update to use the latest NVIDIA GPU Operator and a working install
  playbooks/nvidia-gpu-operator.yml
  roles/nvidia-gpu-operator/defaults/main.yml
  roles/nvidia-gpu-operator/tasks/main.yml
Labels: next-release

#643 Only install helm chart for plugin/operator once
  playbooks/nvidia-gpu-operator.yml
  playbooks/nvidia-k8s-gpu-device-plugin.yml
Labels: next-release

#632 K8s dashboard version updates and access fixes
  .jenkins-scripts/test-dashboard.sh
  config.example/group_vars/k8s-cluster.yml
  scripts/k8s_deploy_dashboard_user.sh
Labels: next-release
