Repository NVIDIA/deepops, pull requests merged in 2022-01, with the labels that each got.

#1079 Update Slurm ElasticSearch logging playbook for log4shell
  playbooks/slurm-cluster/files/cve_2021_44228.options
  playbooks/slurm-cluster/logging.yml
  playbooks/slurm-cluster/templates/filebeat.conf
  roles/requirements.yml
Labels: next-release

#953 Introduce a common script library, config for env vars, and inject these into all scripts
  config.example/env.sh
  docs/deepops/configuration.md
  scripts/airgap/build_offline_cache.sh
  scripts/common.sh
  scripts/generic/install_docker.sh
  scripts/k8s/debug.sh
  scripts/k8s/deploy_dashboard_user.sh
  scripts/k8s/deploy_ingress.sh
  scripts/k8s/deploy_kubeflow.sh
  scripts/k8s/deploy_loadbalancer.sh
  scripts/k8s/deploy_monitoring.sh
  scripts/k8s/deploy_rook.sh
  scripts/k8s/install_helm.sh
  scripts/k8s/setup_remote_k8s.sh
  scripts/k8s/verify_gpu.sh
  scripts/nginx-docker-cache/gen-ca.sh
Labels: no-pr-activity

#1088 Add Molecule testing for Singularity, plus infra for more roles
  .github/workflows/molecule.yml
  docs/deepops/testing.md
  playbooks/container/singularity.yml
  roles/requirements.yml
  roles/singularity_wrapper/.yamllint
  roles/singularity_wrapper/defaults/main.yml
  roles/singularity_wrapper/meta/main.yml
  roles/singularity_wrapper/molecule/default/converge.yml
  roles/singularity_wrapper/molecule/default/molecule.yml
  roles/singularity_wrapper/molecule/default/verify.yml
  roles/singularity_wrapper/tasks/main.yml
  scripts/setup.sh
Labels: nice-to-have-for-release
